### ISSUE TITLE
Selecting Color doesn't update preview

### ISSUE THREAD

**Issue by goodies4uall** [attenzione/android-ColorPickerPreference#28]
I have found a workaround that finishes the settings activity and restarts it. But is there a reason why in ColoPickerPreference the setImageBitmap(getPreviewBitmap()) does not reflect the change when a new color is selected?

If screen is rotated the preview box has the newly selected color.

ICS and Jellybean have this same effect.

**Comment by productigeeky** [comment]
Puting notifyChanged() at the end of setPreviewColor() seems to cause an infinite loop in the draw cycle, causing an overall slowdown. This doesn't happen if you put notifyChanged() at the end of the onColorChanged(int color) method instead.

**Comment by 8804645769** [comment]
Thanks
