### ISSUE TITLE
Sample activity causing trouble because of its placement in the project tree

### ISSUE THREAD

**Issue by JoseGD** [attenzione/android-ColorPickerPreference#33]
The sample activity to showcase the library capabilities (`ColorPickerPreference/src/main/java/net/margaritov/preference/colorpicker/Test.java`) and the manifest file where it is declared (`ColorPickerPreference/src/main/AndroidManifest.xml`) are placed alongside the library sources.

Since settings.gradle has `include ':app', ':ColorPickerPreference'`, that manifest is merged with the main manifest of the app using the library.

As a result, an app that uses the library with the directory tree laid out here ends up with two launcher activities and two icons in the app drawer.

The workaround is commenting the entire `<application>` tag in the manifest, but it would be great to see the sample activity being placed in a different directory not being seen by Gradle - a usual practice in library code.

**Comment by Manabu-GT** [comment]
I'm also having the same issue after importing this library just as in README.
In my case, I put the following line in my main manifest to remove the sample activity included in this library.


<activity android:name="net.margaritov.preference.colorpicker.Test" tools:node="remove"/>

It would be greatly appreciated if you can move the sample activity to a different directory as @JoseGD suggests.
