### ISSUE TITLE
Setting defaultValue

### ISSUE THREAD

**Issue by daxgirl** [attenzione/android-ColorPickerPreference#36]
Hello,
I have been using your ColorPicker in one of my projects and it's by far the best out there. Thank you very much!

I have noticed a little problem and I wanted to offer you a solution I programmed into my project.
There is a little kink in setting the color in attr defaultValue. If you set a color as actual integer, then it works fine, but if you set it as reference to resources, f.e. @color/someColor, you always get 0 in shared preferences. You also can't get it to set defaultValue using hex string.

Both problems are fixed by using this inside onGetDefaultValue method:

    @Override
        protected Object onGetDefaultValue(TypedArray a, int index) {
            int colorInt;
            String mHexDefaultValue = a.getString(index);
            if (mHexDefaultValue != null) {
                colorInt = convertToColorInt(mHexDefaultValue);
                return colorInt;

        } else {
            return a.getColor(index, Color.BLACK);
        }
    }

I have tested repeatedly and now it sets the actual integer value if you use either proper hex string (6 or 8 chars) or reference to resource color.

If you find this useful, feel free to include.

Thank you again for your great work,
Anna

**Comment by attenzione** [comment]
Thank you! You can create pull request and i will merge it
