### ISSUE TITLE
Not Available

### ISSUE THREAD

**Issue by DtotheZ** [attenzione/android-ColorPickerPreference#38]
Hi,
this files are no longer available:

Error:A problem occurred configuring project ':app'.

> Could not find android-ColorPickerPreference.jar (com.github.attenzione:android-ColorPickerPreference:e3aa301016).
>   Searched in the following locations:
>       https://jitpack.io/com/github/attenzione/android-ColorPickerPreference/e3aa301016/android-ColorPickerPreference-e3aa301016.jar

Please fix this. Thank you very much!

**Comment by jitpack-io** [comment]
Hi @DtotheZ 
Have you tried `com.github.attenzione:android-ColorPickerPreference:e3aa301016@aar` ?
